name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  workspace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Run workspace tests
        run: cargo test --manifest-path Cargo.toml --workspace
